# Generated by Django 5.0.7 on 2024-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
